"""Add repository models

Revision ID: ab7e7c5e64ed
Revises: 5d4e6f708192
Create Date: 2026-08-12 00:19:00.415527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab7e7c5e64ed'
down_revision: Union[str, None] = '5d4e6f708192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('files_analyzed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_scan_id'), 'repositories', ['scan_id'], unique=False)
    op.create_table('source_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=True),
    sa.Column('finding_type', sa.String(length=64), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('secret_type', sa.String(length=64), nullable=False),
    sa.Column('redacted_value', sa.String(length=256), nullable=False),
    sa.Column('code_context', sa.Text(), nullable=False),
    sa.Column('package', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('ecosystem', sa.String(length=32), nullable=False),
    sa.Column('advisory_id', sa.String(length=128), nullable=False),
    sa.Column('fixed_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_findings_repository_id'), 'source_findings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_source_findings_scan_id'), 'source_findings', ['scan_id'], unique=False)
    # server_default is required: the scans table already has rows, so a bare
    # NOT NULL add would fail. Column defaults come from the model at insert time.
    op.add_column('scans', sa.Column('fast_scan_homepage_text', sa.Text(), nullable=False, server_default=''))
    op.add_column('scans', sa.Column('fast_scan_homepage_url', sa.String(length=2048), nullable=False, server_default=''))
    op.add_column('scans', sa.Column('repo_info_json', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'repo_info_json')
    op.drop_column('scans', 'fast_scan_homepage_url')
    op.drop_column('scans', 'fast_scan_homepage_text')
    op.drop_index(op.f('ix_source_findings_scan_id'), table_name='source_findings')
    op.drop_index(op.f('ix_source_findings_repository_id'), table_name='source_findings')
    op.drop_table('source_findings')
    op.drop_index(op.f('ix_repositories_scan_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
